spring:
  profiles:
   active: qa

---

spring:
  profiles: dev

server:
  port: 9090

default:
  course:
    name: Uzoka Frank Nice
    chapterCount: 3

course:
  name: Docker and AWS Nice
  chapterCount: 44
  rating: 5
  author: Uzoka Frank


---

spring:
  profiles: qa

server:
  port: 9091

default:
  course:
    name: Uzoka Frank Nice_
    chapterCount: 3_

course:
  name: Docker and AWS Nice_
  chapterCount: 440
  rating: 50
  author: Uzoka Frank_

